import Apple from "./../images/fruitcard/apple.png";
import Banana from "./../images/fruitcard/banana.png";
import Grapes from "./../images/fruitcard/grapes.png";
import Kiwi from "./../images/fruitcard/kiwi.png";
import Mango from "./../images/fruitcard/mango.png";
import Orange from "./../images/fruitcard/orange.png";
import Pineapple from "./../images/fruitcard/pinea.png";
import Strawberry from "./../images/fruitcard/strawberry.png";
import Tomato from "./../images/fruitcard/tomato.png";
import Watermelon from "./../images/fruitcard/watermellon.png";
import Lime from "./../images/fruitcard/lime.png";
import Lemon from "./../images/fruitcard/lemmon.png";
import Pear from "./../images/fruitcard/pear.png";
import Peach from "./../images/fruitcard/peach.png";
import Pomegranate from "./../images/fruitcard/pomoganate.png";
import Avocado from "./../images/fruitcard/avacardo.png";
import Plum from "./../images/fruitcard/plum.png";
import Blueberry from "./../images/fruitcard/Blueberry.png";
import Raspberry from "./../images/fruitcard/raspberry.png";
import Coconut from "./../images/fruitcard/coconut.png";



const cardData = [
    {
        id: "1",
        title: "Tomato",
        description: "A juicy, red vegetable often used in salads and sauces.",
        image: Tomato,
        price: "₹50/kg",
        oldPrice: "₹60/kg",
        quantity: "1 kg",
        shelfLife: "1 week",
        farmer: "Jagdish Gupta",
        manufacturer: "Kaira District Co-operative Milk Producers' Union Limited, Anand 388 001. Lic. No. - 10014021001010.",
        sellerFSSAI: "13323999000106",
        marketedBy: "Green Valley Farms, Aundh, Pune 411007.",
        healthBenefits: "Rich in vitamin C, potassium, and antioxidants like lycopene, which may reduce the risk of heart disease and cancer.",
        storageTemperature: "7-10°C",
        storageType: "Refrigeration",
        imageSlider: [Raspberry, Coconut, Tomato]
    },
    {
        id: "2",
        title: "Apple",
        description: "A delicious, sweet fruit available in various colors.",
        image: Apple,
        price: "₹80/kg",
        oldPrice: "₹100/kg",
        quantity: "1 kg",
        shelfLife: "2 weeks",
        farmer: "Aarti Devi",
        manufacturer: "Sangli Farmers Union, Sangli 416 416. Lic. No. - 10024031001111.",
        sellerFSSAI: "24345678000101",
        marketedBy: "Hilltop Orchard, Mussoorie 248179.",
        healthBenefits: "High in fiber, vitamin C, and antioxidants. Promotes heart health, supports weight management, and reduces the risk of diabetes.",
        storageTemperature: "0-4°C",
        storageType: "Refrigeration",
        imageSlider: [Apple, Apple, Apple]
    },
    {
        id: "3",
        title: "Mango",
        description: "A tropical fruit known for its sweet and tangy flavor.",
        image: Mango,
        price: "₹120/kg",
        oldPrice: "₹140/kg",
        quantity: "1 kg",
        shelfLife: "1 week",
        farmer: "Balram Singh",
        manufacturer: "Pune Agricultural Produce Union, Pune 411 028. Lic. No. - 10034041001212.",
        sellerFSSAI: "15348799000102",
        marketedBy: "Sunshine Farms, Sector 20, Noida 201301.",
        healthBenefits: "Rich in vitamin C and vitamin A, promotes immune health, improves digestion, and supports healthy skin and eyes.",
        storageTemperature: "10-13°C",
        storageType: "Room Temperature",
        imageSlider: [Mango, Mango, Mango]
    },
    {
        id: "4",
        title: "Watermelon",
        description: "A large, juicy fruit with a sweet and refreshing taste.",
        image: Watermelon,
        price: "₹60/piece",
        oldPrice: "₹70/piece",
        quantity: "1 piece",
        shelfLife: "2 weeks",
        farmer: "Chandan Yadav",
        manufacturer: "Nashik Farmers Association, Nashik 422 001. Lic. No. - 10044051001313.",
        sellerFSSAI: "16357891000103",
        marketedBy: "Farmers Choice, Gandhi Nagar, Ahmedabad 382010.",
        healthBenefits: "Rich in vitamins A, B6, and C, contains antioxidants, promotes hydration, and may help reduce muscle soreness.",
        storageTemperature: "10-15°C",
        storageType: "Room Temperature",
        imageSlider: [Watermelon,"https://i.pinimg.com/236x/1e/a7/a9/1ea7a9f76ef5487ed6f0e04286a48126.jpg", "https://i.pinimg.com/236x/3c/8e/1a/3c8e1a7fbde38b0a2f2c92190a83be99.jpg", "https://i.pinimg.com/236x/f5/52/25/f5522551c5a750869e2453979df67264.jpg"]
    },
    {
        id: "5",
        title: "Banana",
        description: "A yellow, curved fruit known for its potassium content.",
        image: Banana,
        price: "₹40/dozen",
        oldPrice: "₹50/dozen",
        quantity: "1 dozen",
        shelfLife: "1 week",
        farmer: "Dheeraj Patel",
        manufacturer: "Kolhapur Fruit Farmers Union, Kolhapur 416 003. Lic. No. - 10054061001414.",
        sellerFSSAI: "27348992000104",
        marketedBy: "Bharat Agro Farms, MG Road, Bengaluru 560001.",
        healthBenefits: "High in potassium, supports heart health, aids digestion, and provides quick energy.",
        storageTemperature: "12-15°C",
        storageType: "Room Temperature",
        imageSlider: [Banana, Banana, Banana]
    },
    {
        id: "6",
        title: "Pineapple",
        description: "A tropical fruit with a sweet and tangy flavor and a spiky exterior.",
        image: Pineapple,
        price: "₹100/piece",
        oldPrice: "₹120/piece",
        quantity: "1 piece",
        shelfLife: "2 weeks",
        farmer: "Ganesh Sharma",
        manufacturer: "Ratnagiri Farmers Co-operative, Ratnagiri 415 612. Lic. No. - 10064071001515.",
        sellerFSSAI: "28356093000105",
        marketedBy: "Citrus Delight, Fort Kochi, Ernakulam 682001.",
        healthBenefits: "Rich in vitamin C, manganese, and digestive enzymes like bromelain, which can aid digestion and reduce inflammation.",
        storageTemperature: "7-10°C",
        storageType: "Refrigeration",
        imageSlider: [Pineapple, Pineapple, Pineapple]
    },
    {
        id: "7",
        title: "Grapes",
        description: "Small, round fruits that come in various colors and flavors.",
        image: Grapes,
        price: "₹80/kg",
        oldPrice: "₹90/kg",
        quantity: "1 kg",
        shelfLife: "1 week",
        farmer: "Hari Prasad",
        manufacturer: "Solapur Grapes Association, Solapur 413 001. Lic. No. - 10074081001616.",
        sellerFSSAI: "29367194000106",
        marketedBy: "Vineyards Direct, MG Road, Hyderabad 500001.",
        healthBenefits: "High in antioxidants like resveratrol, supports heart health, and may help reduce the risk of certain cancers.",
        storageTemperature: "0-4°C",
        storageType: "Refrigeration",
        imageSlider: [Grapes, Grapes, Grapes]
    },
    {
        id: "8",
        title: "Pomegranate",
        description: "A sweet and tart fruit with numerous seeds surrounded by a juicy membrane.",
        image: Pomegranate,
        price: "₹150/kg",
        oldPrice: "₹170/kg",
        quantity: "1 kg",
        shelfLife: "2 weeks",
        farmer: "Jagdish Gupta",
        manufacturer: "Kaira District Co-operative Milk Producers' Union Limited, Anand 388 001. Lic. No. - 10014021001010.",
        sellerFSSAI: "13323999000106",
        marketedBy: "Orchard Fresh,  Sector 15, Chandigarh 160015.",
        healthBenefits: "Rich in antioxidants, vitamin C, and anti-inflammatory compounds, supports heart health, and may lower blood pressure.",
        storageTemperature: "5-7°C",
        storageType: "Refrigeration",
        imageSlider: [Pomegranate, Pomegranate, Pomegranate]
    },
    {
        id: "9",
        title: "Avocado",
        description: "A creamy fruit often used in salads and guacamole.",
        image: Avocado,
        price: "₹100/piece",
        oldPrice: "₹120/piece",
        quantity: "1 piece",
        shelfLife: "1 week",
        farmer: "Kamaljeet Singh",
        manufacturer: "Chennai Farmers Co-operative, Chennai 600 001. Lic. No. - 10084091001717.",
        sellerFSSAI: "30378295000107",
        marketedBy: "Green Heaven, Juhu, Mumbai 400049.",
        healthBenefits: "Rich in healthy fats, fiber, and vitamins C, E, K, and B6. Supports heart health and helps improve digestion.",
        storageTemperature: "4-6°C",
        storageType: "Refrigeration",
        imageSlider: [Avocado, Avocado, Avocado]
    },
    {
        id: "10",
        title: "Kiwi",
        description: "A fuzzy fruit with a sweet and tangy flavor and green flesh.",
        image: Kiwi,
        price: "₹120/kg",
        oldPrice: "₹140/kg",
        quantity: "1 kg",
        shelfLife: "2 weeks",
        farmer: "Mahesh Verma",
        manufacturer: "Bangalore Fruit Co-operative, Bangalore 560 001. Lic. No. - 10094101001818.",
        sellerFSSAI: "31389396000108",
        marketedBy: "Fruitland, Whitefield, Bengaluru 560066.",
        healthBenefits: "High in vitamin C, fiber, and antioxidants, promotes digestion, supports immune health, and may improve skin texture.",
        storageTemperature: "0-4°C",
        storageType: "Refrigeration",
        imageSlider: [Kiwi, Kiwi, Kiwi]
    },
    {
        id: "11",
        title: "Orange",
        description: "A citrus fruit with a sweet and tangy flavor and a vibrant orange color.",
        image: Orange,
        price: "₹70/kg",
        oldPrice: "₹80/kg",
        quantity: "1 kg",
        shelfLife: "2 weeks",
        farmer: "Naveen Raj",
        manufacturer: "Nagpur Citrus Farmers Union, Nagpur 440 001. Lic. No. - 10104111001919.",
        sellerFSSAI: "32490497000109",
        marketedBy: "Fresh Market, Sector 12, Jaipur 302001.",
        healthBenefits: "Rich in vitamin C, fiber, and antioxidants. Supports immune health, improves skin health, and aids in iron absorption.",
        storageTemperature: "4-8°C",
        storageType: "Refrigeration",
        imageSlider: [Orange, Orange, Orange]
    },
    {
        id: "12",
        title: "Peach",
        description: "A juicy, fuzzy fruit with a sweet and slightly tart flavor.",
        image: Peach,
        price: "₹90/kg",
        oldPrice: "₹110/kg",
        shelfLife: "1 week",
        farmer: "Aarti Devi",
        manufacturer: "Ahmedabad Peach Farmers Association, Ahmedabad 380 001. Lic. No. - 10114121002020.",
        sellerFSSAI: "33491598000110",
        healthBenefits: "Rich in vitamin C, fiber, and antioxidants. Supports immune health, improves skin health, and aids in iron absorption.",
        storageTemperature: "4-8°C",
        storageType: "Refrigeration",
        imageSlider: [Peach, Peach, Peach]
    },
    {
        id: "13",
        title: "Pear",
        description: "A sweet and juicy fruit with a smooth texture and subtle flavor.",
        image: Pear,
        price: "₹90/kg",
        oldPrice: "₹110/kg",
        quantity: "1 kg",
        shelfLife: "2 weeks",
        farmer: "Pooja Yadav",
        manufacturer: "Lucknow Fruit Farmers Union, Lucknow 226 001. Lic. No. - 10124131002121.",
        sellerFSSAI: "34492699000111",
        marketedBy: "Royal Orchards, Sector 5, Gurugram 122001.",
        healthBenefits: "Rich in fiber and vitamin C, supports digestion, promotes heart health, and may help in weight management.",
        storageTemperature: "2-5°C",
        storageType: "Refrigeration",
        imageSlider: [Pear, Pear, Pear]
    },
    {
        id: "14",
        title: "Plum",
        description: "A small, round fruit with a juicy interior and a sweet-tart taste.",
        image: Plum,
        price: "₹70/kg",
        oldPrice: "₹90/kg",
        quantity: "1 kg",
        shelfLife: "1 week",
        farmer: "Chetan Desai",
        manufacturer: "Patna Fruit Co-operative, Patna 800 001. Lic. No. - 10134141002222.",
        sellerFSSAI: "35493700000112",
        marketedBy: "Plum Valley, Thane 400601.",
        healthBenefits: "High in fiber, antioxidants, and vitamin C. Supports digestion and may help reduce the risk of heart disease.",
        storageTemperature: "0-4°C",
        storageType: "Refrigeration",
        imageSlider: [Plum, Plum, Plum]
    },
    {
        id: "15",
        title: "Strawberry",
        description: "A bright red fruit with a sweet flavor and juicy texture.",
        image: Strawberry,
        price: "₹150/kg",
        oldPrice: "₹170/kg",
        quantity: "1 kg",
        shelfLife: "1 week",
        farmer: "Diksha Sharma",
        manufacturer: "Ooty Strawberry Co-operative, Ooty 643 001. Lic. No. - 10144151002323.",
        sellerFSSAI: "36494801000113",
        marketedBy: "Mountain Fresh, Alwar 301001.",
        healthBenefits: "High in vitamin C, manganese, and antioxidants. Supports heart health and may help regulate blood sugar levels.",
        storageTemperature: "2-5°C",
        storageType: "Refrigeration",
        imageSlider: [Strawberry, Strawberry, Strawberry]
    },
    {
        id: "16",
        title: "Blueberry",
        description: "A small, round, and sweet fruit with a deep blue color.",
        image: Blueberry,
        price: "₹150/kg",
        oldPrice: "₹170/kg",
        quantity: "1 kg",
        shelfLife: "1 week",
        farmer: "Ekta Yadav",
        manufacturer: "Shimla Fruit Co-operative, Shimla 171 001. Lic. No. - 10154161002424.",
        sellerFSSAI: "37495902000114",
        marketedBy: "North Harvest, Faridabad 121002.",
        healthBenefits: "Rich in antioxidants, vitamins C and K. Supports brain health and may help reduce oxidative stress.",
        storageTemperature: "0-2°C",
        storageType: "Refrigeration",
        imageSlider: [Blueberry, Blueberry, Blueberry]
    },
    {
        id: "17",
        title: "Raspberry",
        description: "A small, red, and juicy fruit with a tart flavor.",
        image: Raspberry,
        price: "₹180/kg",
        oldPrice: "₹200/kg",
        quantity: "1 kg",
        shelfLife: "1 week",
        farmer: "Farhan Qureshi",
        manufacturer: "Dehradun Farmers Co-operative, Dehradun 248 001. Lic. No. - 10164171002525.",
        sellerFSSAI: "38496003000115",
        marketedBy: "Fruit Haven, Shimla 171001.",
        healthBenefits: "High in fiber, antioxidants, and vitamin C. Supports weight loss and helps reduce inflammation.",
        storageTemperature: "0-2°C",
        storageType: "Refrigeration",
        imageSlider: [Raspberry, Raspberry, Raspberry]
    },
    {
        id: "18",
        title: "Coconut",
        description: "A tropical fruit with a hard shell and sweet, white flesh.",
        image: Coconut,
        price: "₹50/piece",
        oldPrice: "₹60/piece",
        quantity: "1 piece",
        shelfLife: "1 month",
        farmer: "Govind Naidu",
        manufacturer: "Kerala Coconut Farmers Co-operative, Kerala 695 001. Lic. No. - 10174181002626.",
        sellerFSSAI: "39497104000116",
        marketedBy: "Tropical Farms, Kanyakumari 629702.",
        healthBenefits: "High in healthy fats, promotes heart health, and supports brain function.",
        storageTemperature: "10-15°C",
        storageType: "Room Temperature",
        imageSlider: [Coconut, Coconut, Coconut]
    },
    {
        id: "19",
        title: "Lemon",
        description: "A small, yellow citrus fruit with a sour taste.",
        image: Lemon,
        price: "₹40/kg",
        oldPrice: "₹50/kg",
        quantity: "1 kg",
        shelfLife: "2 weeks",
        farmer: "Harish Patil",
        manufacturer: "Mumbai Citrus Farmers Union, Mumbai 400 001. Lic. No. - 10184191002727.",
        sellerFSSAI: "40498205000117",
        marketedBy: "Sunny Orchards, Viman Nagar, Pune 411014.",
        healthBenefits: "Rich in vitamin C, supports immune health, aids digestion, and promotes hydration.",
        storageTemperature: "8-12°C",
        storageType: "Room Temperature",
        imageSlider: [Lemon, Lemon, Lemon]
    },
    {
        id: "20",
        title: "Lime",
        description: "A small, green citrus fruit with a tart and sour flavor.",
        image: Lime,
        price: "₹30/kg",
        oldPrice: "₹40/kg",
        quantity: "1 kg",
        shelfLife: "2 weeks",
        farmer: "Indira Gupta",
        manufacturer: "Goa Fruit Co-operative, Goa 403 001. Lic. No. - 10194201002828.",
        sellerFSSAI: "41499306000118",
        marketedBy: "Tropical Greens, Panaji 403001.",
        healthBenefits: "Rich in vitamin C and antioxidants, supports immune health and helps improve skin quality.",
        storageTemperature: "8-12°C",
        storageType: "Room Temperature",
        imageSlider: [Lime, Lime, Lime]
    }
];

export default cardData;
